<a href="https://colab.research.google.com/github/venkateshreddypala/CSCI-6040/blob/Getting-Started-with-Pytorch/Getting_Started_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Importing required libraries
import torch
import numpy as np
# It will set the seed of the random number generator to a fixed value,
# so that when you call for example torch.rand(2), the results will be reproducible.
# Else it produces results which are random and you'll see that it changes over time.
torch.manual_seed(1234)



# Getting Started with PyTorch, for more documentation and support, visit the official [page](https://pytorch.org/tutorials/)

---
For math operations refer to the following [page](https://pytorch.org/docs/stable/torch.html#math-operations)


---

Reference for Vectors for Word Representation [Glove](https://nlp.stanford.edu/pubs/glove.pdf)



**Tensors**

*Tensors are similar to a matrix in Mathematical representation except they are N-Dimensional arrays of numbers.*

*FloatTensor is the default type of Tensor*

*The other type for Tensor is a Long Tensor, Long Tensors are used for indexing operations and mirror the int64 numpy type*


* We will create Tensors, the shape of the Tensor is determined by the arguments.*





In [0]:
# Sample Tensor  Creation using describe function in Python3
# Here 'y' is a Tensor with 8 rows and 5 columns
def describe(y):
    print("Type: {}".format(y.type()))
    print("Shape/size: {}".format(y.shape))
    print("Values: \n{}".format(y))

In [0]:
describe(torch.Tensor(8,5))

Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[1.1933e-36, 0.0000e+00, 1.9898e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [7.0295e+28, 6.1949e-04, 2.9390e+29, 2.0705e-19, 4.4721e+21],
        [1.8010e+25, 4.7426e+30, 3.0186e+32, 2.1128e-19, 1.2414e+28],
        [3.2304e-18, 1.8371e+25, 7.5551e+31, 2.6543e+20, 3.2607e-12],
        [7.1856e+22, 2.8405e+20, 1.0395e+21, 3.2986e-18, 3.1457e-12],
        [7.5654e+28, 4.2198e+24, 7.5654e+28, 6.1979e-04, 7.2443e+22],
        [1.9421e+31, 6.5950e+22, 7.1555e+22, 7.2250e+28, 6.1970e-04]])


In [0]:
#using rand
describe(torch.randn(8,5))

Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[-1.3892, -0.6208, -0.0242, -1.0402,  0.7988],
        [-0.0923, -0.7049, -1.6024, -1.0257,  1.7473],
        [ 0.8090, -1.0989, -0.1706, -1.4594,  0.2207],
        [ 0.2463,  0.9717, -0.5150,  1.4255,  0.7987],
        [-1.4949,  0.8810, -1.1786, -0.9340, -1.5173],
        [ 0.3877, -1.1849,  0.6897, -0.2833, -0.5660],
        [ 0.3566, -0.4535,  0.0323, -1.6593, -1.8773],
        [ 0.7372,  0.3910,  0.5158, -1.0042,  0.9860]])


It is a common practice to generate random numbers for prototypes

In [0]:
y = torch.rand(2,3)
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.2908, 0.4196, 0.3728],
        [0.3769, 0.0108, 0.9455]])


We can generate Tensors with Zeros and One 

In [0]:
describe(torch.zeros(8, 5))
y = torch.ones(8, 5)
describe(y)
y.fill_(5)
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])


We can fill the numbers after initilization and then fill in place, operation is denoted by (_)

In [12]:
y = torch.Tensor(2,3).fill_(5)
print(y.type())
print(y.shape)
print(y)

torch.FloatTensor
torch.Size([2, 3])
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [13]:
y = torch.Tensor([[2, 3,],  
                  [3, 4,]])
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[2., 3.],
        [3., 4.]])


In [14]:
# LOngTensor
import torch
y = torch.arange(6).view(2, 3)
describe(y)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [16]:
y = torch.FloatTensor([[1, 2, 3],  
                       [4, 5, 6]])
describe(y)

y = y.long()
describe(y)

y = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=torch.int64)
describe(y)

y = y.float() 
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [17]:
y = torch.randn(2, 3)
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.8169,  0.8579, -0.2107],
        [ 1.1399, -2.5122,  1.3823]])


In [18]:
describe(torch.add(y, y))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.6339,  1.7159, -0.4215],
        [ 2.2799, -5.0244,  2.7646]])


In [19]:
describe(y + y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.6339,  1.7159, -0.4215],
        [ 2.2799, -5.0244,  2.7646]])


In [20]:
y = torch.arange(6)
describe(y)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [21]:
y = y.view(2, 3)
describe(y)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [22]:
describe(torch.sum(y, dim=0))
describe(torch.sum(y, dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])
Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [23]:
describe(torch.transpose(y, 0, 1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [24]:
import torch
y = torch.arange(6).view(2, 3)
describe(y)
describe(y[:1, :2])
describe(y[0, 1])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])
Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


In [25]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(y, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [26]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(y, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [27]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(y[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


In [28]:
y = torch.LongTensor([[1, 2, 3],  
                      [4, 5, 6],
                      [7, 8, 9]])
describe(y)
print(y.dtype)
print(y.numpy().dtype)


Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int64
int64


You can Typecast from Tensor type to Long and Vice versa, you can also cast to String using DoubleTensor which is rare.

In [29]:
# Example 
y = torch.FloatTensor([[1, 2, 3],  
                       [4, 5, 6],
                       [7, 8, 9]])
y = y.long()
describe(y)

Type: torch.LongTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [32]:
# Special Tensor Initializations

y = torch.arange(0, 10)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [34]:
y = torch.arange(0, 10).long()
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


**Math Operations in PyTorch**


The foundation for modern deep learning is applying the knowledge of linear algebra by using the Tensors

---

One importnat topic is 'view' which allows to reshape the tenosr as per the requirements.







In [52]:
# Transposing, allows you to switch the dimensions to be on different axis
y = torch.arange(0, 12).view(3,4)
print("y: \n", y) 
print("---")
print("y.tranpose(1, 0): \n", y.transpose(1, 0))

y: 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
---
y.tranpose(1, 0): 
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])




> * A 3-D vector represents a group of sequences. *


> * Each sequence consists of a feature vector, while transpose has a restriction of swapping only 2 axes, permute allows for multiple. *

> 





In [53]:
batch_size = 3
seq_size = 4
feature_size = 5

z = torch.arange(batch_size * seq_size * feature_size).view(batch_size, seq_size, feature_size)

print("z.shape: \n", z.shape)
print("z: \n", z)
print("-----")

print("z.transpose(1, 0).shape: \n", z.transpose(1, 0).shape)
print("z.transpose(1, 0): \n", z.transpose(1, 0))

z.shape: 
 torch.Size([3, 4, 5])
z: 
 tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
-----
z.transpose(1, 0).shape: 
 torch.Size([4, 3, 5])
z.transpose(1, 0): 
 tensor([[[ 0,  1,  2,  3,  4],
         [20, 21, 22, 23, 24],
         [40, 41, 42, 43, 44]],

        [[ 5,  6,  7,  8,  9],
         [25, 26, 27, 28, 29],
         [45, 46, 47, 48, 49]],

        [[10, 11, 12, 13, 14],
         [30, 31, 32, 33, 34],
         [50, 51, 52, 53, 54]],

        [[15, 16, 17, 18, 19],
         [35, 36, 37, 38, 39],
         [55, 56, 57, 58, 59]]])


In [54]:
# MAtrix multiplication is denoted by mm
torch.randn(2, 3, requires_grad=True)

tensor([[ 0.5236,  0.2712, -0.3281],
        [-0.0684,  0.7300, -0.9683]], requires_grad=True)

In [56]:
y1 = torch.arange(6).view(2, 3).float()
describe(y1)

y2 = torch.ones(3, 2)
y2[:, 1] += 1
describe(y2)

describe(torch.mm(y1, y2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [57]:
y = torch.arange(0, 12).view(3,4).float()
print(y)

y2 = torch.ones(4, 2)
y2[:, 1] += 1
print(y2)

print(y.mm(y2))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[1., 2.],
        [1., 2.],
        [1., 2.],
        [1., 2.]])
tensor([[ 6., 12.],
        [22., 44.],
        [38., 76.]])


In [40]:

#After view the total should remain the same
y = torch.arange(0,20)

print (y.view(1,20))
print (y.view(2,10))
print (y.view(5,4))
print (y.view(4,5))
print (y.view(10,2))
print (y.view(20,1))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])


**BraodCasting**


*we can use view to ass size -1 dimmensions, which is useful for combining with other tensors*

In [41]:
# Example
x = torch.arange(12).view(3, 4)
y = torch.arange(4).view(1, 4)
z = torch.arange(3).view(3, 1)

print(x)
print(y)
print(z)
print(x + y)
print(x + z)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0, 1, 2, 3]])
tensor([[0],
        [1],
        [2]])
tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]])
tensor([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]])


**Unsqueeze and squeeze will add and remove 1-dimensions.**

*This might be confused with view but three's a significant difference 'view' cannot add additional dimension to the existing tensor where as Unsqueeze will add and dimension*




In [42]:
# intitally we have a 3,4 Vector, we are adding one using Unsquueze function and
# then using squeeze we are bringing it back to its regular position.
z = torch.arange(12).view(3, 4)
print(z.shape)

z = z.unsqueeze(dim=1)
print(z.shape)

z = z.squeeze()
print(z.shape)

torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4])


In [43]:
# all of the standard mathematics operations apply (such as add below)
x = torch.rand(3,4)
print("x: \n", x)
print("--")
print("torch.add(x, x): \n", torch.add(x, x))
print("--")
print("x+x: \n", x + x)

x: 
 tensor([[0.7695, 0.0378, 0.2239, 0.6772],
        [0.5274, 0.6325, 0.0910, 0.2323],
        [0.7269, 0.1187, 0.3951, 0.7199]])
--
torch.add(x, x): 
 tensor([[1.5390, 0.0757, 0.4479, 1.3545],
        [1.0548, 1.2650, 0.1819, 0.4646],
        [1.4537, 0.2375, 0.7902, 1.4398]])
--
x+x: 
 tensor([[1.5390, 0.0757, 0.4479, 1.3545],
        [1.0548, 1.2650, 0.1819, 0.4646],
        [1.4537, 0.2375, 0.7902, 1.4398]])


In [45]:
# the convention of _ indicating in-place operations continues:
y = torch.arange(12).reshape(3, 4)
print(y)
print(y.add_(y))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])


In [46]:
# There are many operations for which reduce a dimension. Such as sum:

y = torch.arange(12).reshape(3, 4)
print("y: \n", y)
print("---")
print("Summing across rows (dim=0): \n", y.sum(dim=0))
print("---")
print("Summing across columns (dim=1): \n", y.sum(dim=1))

y: 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
---
Summing across rows (dim=0): 
 tensor([12, 15, 18, 21])
---
Summing across columns (dim=1): 
 tensor([ 6, 22, 38])


**Join, Index, Slice functions in PyTorch**

In [47]:
y = torch.arange(6).view(2, 3)
print("y: \n", y)
print("---")
print("y[:2, :2]: \n", y[:2, :2])
print("---")
print("y[0][1]: \n", y[0][1])
print("---")
print("Setting [0][1] to be 8")
y[0][1] = 8
print(y)

y: 
 tensor([[0, 1, 2],
        [3, 4, 5]])
---
y[:2, :2]: 
 tensor([[0, 1],
        [3, 4]])
---
y[0][1]: 
 tensor(1)
---
Setting [0][1] to be 8
tensor([[0, 8, 2],
        [3, 4, 5]])


In [48]:
# A subset of a tensor can be selected using index_select
y = torch.arange(9).view(3,3)
print(y)

print("---")
indices = torch.LongTensor([0, 2])
print(torch.index_select(y, dim=0, index=indices))

print("---")
indices = torch.LongTensor([0, 2])
print(torch.index_select(y, dim=1, index=indices))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
---
tensor([[0, 1, 2],
        [6, 7, 8]])
---
tensor([[0, 2],
        [3, 5],
        [6, 8]])


In [49]:
# Padding a Zero, popular in several Neural Networks
y = torch.arange(9).view(3,3)
print(y)
print("---")
new_y = torch.stack([y, y, y])
print(new_y.shape)
print(new_y)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
---
torch.Size([3, 3, 3])
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])


In [50]:
#Concatination of columns

y = torch.arange(9).view(3,3)

print(y)
print("---")
new_y = torch.cat([y, y, y], dim=1)
print(new_y.shape)
print(new_y)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
---
torch.Size([3, 9])
tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8, 6, 7, 8]])


In [51]:
# Concatinating row-wise
y = torch.arange(6).view(2,3)
describe(y)
describe(torch.cat([y, y], dim=0))
describe(torch.cat([y, y], dim=1))
describe(torch.stack([y, y]))


Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


# Computation of Gradients

In [59]:
x = torch.tensor([[2.0, 3.0]], requires_grad=True)
z = 3 * x
print(z)

tensor([[6., 9.]], grad_fn=<MulBackward0>)


In [60]:
x = torch.tensor([[2.0, 3.0]], requires_grad=True)
print("x: \n", x)
print("---")
z = 3 * x
print("z = 3*x: \n", z)
print("---")

loss = z.sum()
print("loss = z.sum(): \n", loss)
print("---")

loss.backward()

print("after loss.backward(), x.grad: \n", x.grad)

x: 
 tensor([[2., 3.]], requires_grad=True)
---
z = 3*x: 
 tensor([[6., 9.]], grad_fn=<MulBackward0>)
---
loss = z.sum(): 
 tensor(15., grad_fn=<SumBackward0>)
---
after loss.backward(), x.grad: 
 tensor([[3., 3.]])


*Output is formatted to a scalar to calculate the loss variable, Now after this we perform a backward propagation on the loss to determine the rate of change with respect to given inputs.*

* The rate of change is the constant 3, which we multipled with the variable x. *

In [0]:
# Example for a conditional gradient. sin(x) for x>0 and cos(x) for x<0
def f(x):
  if (x.data > 0).all():
    return torch.sin(x)
  else: 
    return torch.cos(x)

In [62]:
y = torch.tensor([1.0], requires_grad=True)
z = f(y)
z.backward()
print(y.grad)

tensor([0.5403])


**We need to make sure the output is a scalar**

*We use masking to make sure the computation is performed elementwise*

In [63]:
def f2(x):
    mask = torch.gt(x, 0).float()
    return mask * torch.sin(x) + (1 - mask) * torch.cos(x)

x = torch.tensor([1.0, -1], requires_grad=True)
y = f2(x)
y.sum().backward()
print(x.grad)


tensor([0.5403, 0.8415])


In [0]:
def describe_grad(x):
    if x.grad is None:
        print("No gradient information")
    else:
        print("Gradient: \n{}".format(x.grad))
        print("Gradient Function: {}".format(x.grad_fn))

In [66]:
import torch
x = torch.ones(2, 2, requires_grad=True)
describe(x)
describe_grad(x)
print("--------")

y = (x + 2) * (x + 5) + 3
describe(y)
z = y.mean()
describe(z)
describe_grad(x)
print("--------")
z.backward(create_graph=True, retain_graph=True)
describe_grad(x)
print("--------")

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
No gradient information
--------
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
No gradient information
--------
Gradient: 
tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]], grad_fn=<CloneBackward>)
Gradient Function: None
--------


In [0]:
x = torch.ones(2, 2, requires_grad=True)

In [0]:
y = x + 2

In [69]:
y.grad_fn