<a href="https://colab.research.google.com/github/venkateshreddypala/CSCI-6040/blob/Getting-Started-with-Pytorch/Getting_Started_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Importing required libraries
import torch
import numpy as np
# It will set the seed of the random number generator to a fixed value,
# so that when you call for example torch.rand(2), the results will be reproducible.
# Else it produces results which are random and you'll see that it changes over time.
torch.manual_seed(1234)



# Getting Started with PyTorch, for more documentation and support, visit the official [page](https://pytorch.org/tutorials/)

---



**Tensors**

*Tensors are similar to a matrix in Mathematical representation except they are N-Dimensional arrays of numbers.*

* We will create Tensors, the shape of the Tensor is determined by the arguments.*





In [0]:
# Sample Tensor  Creation using describe function in Python3
# Here 'y' is a Tensor with 8 rows and 5 columns
def describe(y):
    print("Type: {}".format(y.type()))
    print("Shape/size: {}".format(y.shape))
    print("Values: \n{}".format(y))

In [0]:
describe(torch.Tensor(8,5))

Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[1.1933e-36, 0.0000e+00, 1.9898e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [7.0295e+28, 6.1949e-04, 2.9390e+29, 2.0705e-19, 4.4721e+21],
        [1.8010e+25, 4.7426e+30, 3.0186e+32, 2.1128e-19, 1.2414e+28],
        [3.2304e-18, 1.8371e+25, 7.5551e+31, 2.6543e+20, 3.2607e-12],
        [7.1856e+22, 2.8405e+20, 1.0395e+21, 3.2986e-18, 3.1457e-12],
        [7.5654e+28, 4.2198e+24, 7.5654e+28, 6.1979e-04, 7.2443e+22],
        [1.9421e+31, 6.5950e+22, 7.1555e+22, 7.2250e+28, 6.1970e-04]])


In [0]:
#using rand
describe(torch.randn(8,5))

Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[-1.3892, -0.6208, -0.0242, -1.0402,  0.7988],
        [-0.0923, -0.7049, -1.6024, -1.0257,  1.7473],
        [ 0.8090, -1.0989, -0.1706, -1.4594,  0.2207],
        [ 0.2463,  0.9717, -0.5150,  1.4255,  0.7987],
        [-1.4949,  0.8810, -1.1786, -0.9340, -1.5173],
        [ 0.3877, -1.1849,  0.6897, -0.2833, -0.5660],
        [ 0.3566, -0.4535,  0.0323, -1.6593, -1.8773],
        [ 0.7372,  0.3910,  0.5158, -1.0042,  0.9860]])


It is a common practice to generate random numbers for prototypes

In [0]:
y = torch.rand(2,3)
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.2908, 0.4196, 0.3728],
        [0.3769, 0.0108, 0.9455]])


We can generate Tensors with Zeros and One 

In [0]:
describe(torch.zeros(8, 5))
y = torch.ones(8, 5)
describe(y)
y.fill_(5)
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([8, 5])
Values: 
tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])


We can fill the numbers after initilization and then fill in place, operation 